import type { AiCategoryName } from '@aieng/shared';

export interface SeedProblem {
  slug: string;
  title: string;
  topic: AiCategoryName;
  difficulty: 'easy' | 'medium' | 'hard';
  type: 'mcq';
  prompt: string;
  options: string[];
  correctAnswer: string;
  order: number;
}

export const SEED_PROBLEMS: SeedProblem[] = [
  {
    slug: 'prompt-engineering-1',
    title: 'Prompt clarity',
    topic: 'Prompt Engineering',
    difficulty: 'easy',
    type: 'mcq',
    prompt:
      'Which prompt best follows the instruction to return JSON only with keys "title" and "summary"?',
    options: [
      'Write about AI and make it sound smart.',
      'Return JSON with keys title and summary for this article: …',
      'Explain AI in 500 words, then add a title at the end.',
      'Summarize this but feel free to use markdown.',
    ],
    correctAnswer: 'Return JSON with keys title and summary for this article: …',
    order: 1,
  },
  {
    slug: 'prompt-engineering-2',
    title: 'Few-shot prompting',
    topic: 'Prompt Engineering',
    difficulty: 'medium',
    type: 'mcq',
    prompt: 'What is the main purpose of few-shot examples in a prompt?',
    options: [
      'To increase model parameter count',
      'To show the model the desired input/output pattern',
      'To disable the model safety layer',
      'To reduce token usage to zero',
    ],
    correctAnswer: 'To show the model the desired input/output pattern',
    order: 2,
  },
  {
    slug: 'prompt-engineering-3',
    title: 'Chain-of-thought',
    topic: 'Prompt Engineering',
    difficulty: 'medium',
    type: 'mcq',
    prompt: 'Chain-of-thought prompting is most useful when you need the model to…',
    options: [
      'Skip reasoning and answer immediately',
      'Show intermediate reasoning steps before the final answer',
      'Only return emojis',
      'Ignore the user instructions',
    ],
    correctAnswer: 'Show intermediate reasoning steps before the final answer',
    order: 3,
  },
  {
    slug: 'llm-fundamentals-1',
    title: 'Next-token prediction',
    topic: 'Large Language Models',
    difficulty: 'easy',
    type: 'mcq',
    prompt: 'Autoregressive LLMs generate text by repeatedly predicting…',
    options: ['The entire document at once', 'The next token', 'A random seed', 'User embeddings'],
    correctAnswer: 'The next token',
    order: 4,
  },
  {
    slug: 'llm-fundamentals-2',
    title: 'Context window',
    topic: 'Large Language Models',
    difficulty: 'easy',
    type: 'mcq',
    prompt: 'The context window limit primarily constrains…',
    options: [
      'How many tokens the model can attend to in one request',
      'The number of GPUs in the cluster',
      'The size of the training dataset in terabytes',
      'The number of users on the platform',
    ],
    correctAnswer: 'How many tokens the model can attend to in one request',
    order: 5,
  },
  {
    slug: 'llm-fundamentals-3',
    title: 'Temperature',
    topic: 'Large Language Models',
    difficulty: 'medium',
    type: 'mcq',
    prompt: 'Lowering sampling temperature during inference generally makes outputs…',
    options: ['More random and diverse', 'More deterministic and focused', 'Slower to train', 'Longer context windows'],
    correctAnswer: 'More deterministic and focused',
    order: 6,
  },
  {
    slug: 'rag-basics-1',
    title: 'RAG purpose',
    topic: 'Generative AI',
    difficulty: 'easy',
    type: 'mcq',
    prompt: 'Retrieval-Augmented Generation (RAG) mainly helps LLMs by…',
    options: [
      'Replacing the need for any model weights',
      'Grounding answers with retrieved external documents',
      'Eliminating latency entirely',
      'Training the model from scratch each query',
    ],
    correctAnswer: 'Grounding answers with retrieved external documents',
    order: 7,
  },
  {
    slug: 'rag-basics-2',
    title: 'Chunking strategy',
    topic: 'Generative AI',
    difficulty: 'medium',
    type: 'mcq',
    prompt: 'When building a RAG pipeline, chunking documents is important because…',
    options: [
      'It guarantees 100% factual answers',
      'It balances retrieval precision with context size limits',
      'It removes the need for embeddings',
      'It disables duplicate detection',
    ],
    correctAnswer: 'It balances retrieval precision with context size limits',
    order: 8,
  },
  {
    slug: 'rag-basics-3',
    title: 'Hybrid search',
    topic: 'Natural Language Processing',
    difficulty: 'hard',
    type: 'mcq',
    prompt: 'Hybrid retrieval often combines dense vector search with keyword search to…',
    options: [
      'Increase storage costs only',
      'Improve recall on both semantic and exact-match queries',
      'Remove the reranking step',
      'Avoid indexing documents',
    ],
    correctAnswer: 'Improve recall on both semantic and exact-match queries',
    order: 9,
  },
  {
    slug: 'agents-1',
    title: 'Tool use',
    topic: 'AI Agents',
    difficulty: 'easy',
    type: 'mcq',
    prompt: 'In an LLM agent, a "tool" is best described as…',
    options: [
      'A fixed hard-coded if/else branch only',
      'An external capability the model can invoke via structured calls',
      'A GPU kernel',
      'A database migration script',
    ],
    correctAnswer: 'An external capability the model can invoke via structured calls',
    order: 10,
  },
  {
    slug: 'agents-2',
    title: 'ReAct pattern',
    topic: 'AI Agents',
    difficulty: 'medium',
    type: 'mcq',
    prompt: 'The ReAct pattern interleaves reasoning traces with…',
    options: ['Random sampling', 'Actions and observations', 'Gradient updates', 'Token pruning only'],
    correctAnswer: 'Actions and observations',
    order: 11,
  },
  {
    slug: 'agents-3',
    title: 'Agent safety',
    topic: 'Responsible AI',
    difficulty: 'medium',
    type: 'mcq',
    prompt: 'Before giving an agent access to send emails, a key safety control is…',
    options: [
      'No logging of actions',
      'Human approval or scoped permissions for destructive actions',
      'Unlimited tool retries',
      'Disabling all authentication',
    ],
    correctAnswer: 'Human approval or scoped permissions for destructive actions',
    order: 12,
  },
  {
    slug: 'eval-metrics-1',
    title: 'BLEU vs human eval',
    topic: 'Natural Language Processing',
    difficulty: 'easy',
    type: 'mcq',
    prompt: 'BLEU is often insufficient alone for LLM evaluation because…',
    options: [
      'It captures semantic correctness and safety well',
      'It measures n-gram overlap, not meaning or factuality',
      'It requires no reference text',
      'It only works on code',
    ],
    correctAnswer: 'It measures n-gram overlap, not meaning or factuality',
    order: 13,
  },
  {
    slug: 'eval-metrics-2',
    title: 'LLM-as-judge',
    topic: 'Generative AI',
    difficulty: 'medium',
    type: 'mcq',
    prompt: 'Using an LLM as a judge is useful but requires…',
    options: [
      'No calibration or human spot checks',
      'Careful rubrics and periodic human validation',
      'Disabling all metrics',
      'Only multiple-choice questions',
    ],
    correctAnswer: 'Careful rubrics and periodic human validation',
    order: 14,
  },
  {
    slug: 'eval-metrics-3',
    title: 'Golden sets',
    topic: 'Machine Learning',
    difficulty: 'medium',
    type: 'mcq',
    prompt: 'A golden evaluation set should be…',
    options: [
      'Identical to the training set',
      'A held-out, labeled set representing real user tasks',
      'Generated only by the model under test',
      'Updated after every production request',
    ],
    correctAnswer: 'A held-out, labeled set representing real user tasks',
    order: 15,
  },
  {
    slug: 'mlops-1',
    title: 'Model registry',
    topic: 'MLOps',
    difficulty: 'easy',
    type: 'mcq',
    prompt: 'An ML model registry primarily tracks…',
    options: [
      'Only frontend bundle sizes',
      'Versioned models, metadata, and deployment lineage',
      'User passwords',
      'CSS theme tokens',
    ],
    correctAnswer: 'Versioned models, metadata, and deployment lineage',
    order: 16,
  },
  {
    slug: 'mlops-2',
    title: 'Shadow deployment',
    topic: 'MLOps',
    difficulty: 'hard',
    type: 'mcq',
    prompt: 'Shadow deployment means…',
    options: [
      'Replacing production traffic immediately',
      'Running a new model on duplicate traffic without serving its outputs to users',
      'Deleting the old model before testing',
      'Training only on synthetic data',
    ],
    correctAnswer: 'Running a new model on duplicate traffic without serving its outputs to users',
    order: 17,
  },
  {
    slug: 'embeddings-1',
    title: 'Vector similarity',
    topic: 'Deep Learning',
    difficulty: 'easy',
    type: 'mcq',
    prompt: 'Cosine similarity between embedding vectors measures…',
    options: [
      'The angle between vectors (directional similarity)',
      'The exact byte length of documents',
      'GPU temperature',
      'SQL join performance',
    ],
    correctAnswer: 'The angle between vectors (directional similarity)',
    order: 18,
  },
];
